version: '3.8'

services:
  # 1. SERVICIO DE BASE DE DATOS (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: apis
      MYSQL_DATABASE: apis
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. SERVICIO DE BACKEND (Spring Boot)
  backend:
    # El contexto (context) es la carpeta 'e_commerce' dentro del directorio actual (TPO - Grupo 5/)
    build:
      context: ./e_commerce
      dockerfile: Dockerfile  # Asume que el Dockerfile del Back está en e_commerce/
    container_name: spring-backend-ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - db

  # 3. SERVICIO DE FRONTEND (React/Nginx)
  frontend:
    # El contexto (context) es el directorio actual (TPO - Grupo 5/)
    build:
      context: . 
      # Usamos el Dockerfile que colocamos en la raíz de TPO - Grupo 5/
      dockerfile: Dockerfile.frontend 
    container_name: react-frontend-ecommerce
    ports:
      - "80:80"
    depends_on:
      - backend # Depende del backend para que el proxy funcione correctamente

volumes:
  mysql_data: