version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: apis
      MYSQL_DATABASE: apis
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: jlopezkorach/tpo-grupo5-backend:1.0
    container_name: spring-backend-ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: jlopezkorach/tpo-grupo5-frontend:1.0
    container_name: react-frontend-ecommerce
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: